=== rmlgc/examen_XSD/lloguer.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:h="http://www.iessonferrer.net/jgonzalez/lloguerCotxes"
targetNamespace="http://www.iessonferrer.net/jgonzalez/lloguerCotxes"
elementFormDefault="qualified">
	<xsd:element name="lloguerCotxes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="cotxe" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="marca" type="xsd:string"/>
							<xsd:element name="model" type="xsd:string"/>
							<xsd:element name="color" type="xsd:string" minOccurs="0"/>
							<xsd:element name="equipacio">
								<xsd:complexType>
            					<xsd:all>
										<xsd:element name="climatitzador" type="xsd:string"/>
										<xsd:element name="airbagsLaterals" type="xsd:string"/>
										<xsd:element name="automatic" type="xsd:string"/>
										<xsd:element name="cadiraNinPetit" type="xsd:string"/>
									</xsd:all>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="matricula"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="client" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="nom" maxOccurs="10">
								<xsd:complexType>
								    <xsd:simpleContent>
								        <xsd:extension base="xsd:string">
								            <xsd:attribute name="tractament" type="h:tractament" use="required"/>
								        </xsd:extension>
								    </xsd:simpleContent>
								</xsd:complexType>
						   </xsd:element>
							<xsd:element name="telefon">
								<xsd:simpleType>
									<xsd:restriction base="xsd:integer">
										<xsd:minInclusive value="971230000"/>
										<xsd:maxInclusive value="971239999"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>

							<xsd:element name="email" type="h:emailAddress"/>
							<xsd:element name="tipusClient" type="h:tipus"/>
							<xsd:element name="lloguer" maxOccurs="unbounded">
								<xsd:complexType>
            					<xsd:all>
										<xsd:element name="cotxe" type="xsd:string"/>
										<xsd:element name="dataInici" type="xsd:date"/>
										<xsd:element name="dataFi" type="xsd:date"/>
									</xsd:all>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
							<xsd:attribute name="dni"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="tractament">
   	<xsd:restriction base="xsd:string">
      	<xsd:pattern value="Sr|Sra"/>
   	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipus">
   	<xsd:restriction base="xsd:string">
   		<xsd:pattern value="Premium|Ocasional"/>
   	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="emailAddress"> 
    	<xsd:restriction base="xsd:string"> 
   		<xsd:pattern value="[^@]+@[^\.]+\..+"/> 
   	</xsd:restriction> 
	</xsd:simpleType>
<!--	<xsd:key name="matriculakey">
   	<xsd:selector xpath="h:cotxe"/>
   		<xsd:field xpath="@matricula"/>
   </xsd:key>
	<xsd:keyref name="lloguerkeyref" refer="h:matriculakey">
   	<xsd:selector xpath="h:lloguer"/>
   	<xsd:field xpath="@cotxe"/>
   </xsd:keyref>-->
</xsd:schema>

=== rmlgc/examen_XSD/lloguer.xml
<lloguerCotxes xmlns="http://www.iessonferrer.net/jgonzalez/lloguerCotxes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.iessonferrer.net/jgonzalez/lloguerCotxes lloguer.xsd">
	<cotxe matricula="4256DRL">
		<marca>Seat</marca>
		<model>Alhambra</model>
		<equipacio>
			<climatitzador>Si</climatitzador>
			<airbagsLaterals>Si</airbagsLaterals>
			<automatic>No</automatic>
			<cadiraNinPetit>Opcional</cadiraNinPetit>
		</equipacio>
	</cotxe>
	<cotxe matricula="5258DRL">
		<marca>Volkswagen</marca>
		<model>Golf</model>
		<color>Negre</color>
		<equipacio>
			<climatitzador>Opcional</climatitzador>
			<airbagsLaterals>Si</airbagsLaterals>
			<automatic>Si</automatic>
			<cadiraNinPetit>No</cadiraNinPetit>
		</equipacio>
	</cotxe>

	<client dni="42568525z">
		<nom tractament="Sr">Antoni Pascual</nom>
		<telefon>971230546</telefon>
		<email>apascual@gmail.com</email>
		<tipusClient>Premium</tipusClient>
		<lloguer>
			<cotxe>5258DRL</cotxe>
			<dataInici>2016-03-12</dataInici>
			<dataFi>2016-03-20</dataFi>
		</lloguer>
		<lloguer>
			<cotxe>5258DRL</cotxe>
			<dataInici>2016-04-12</dataInici>
			<dataFi>2016-04-20</dataFi>
		</lloguer>
		<lloguer>
			<cotxe>5258DRL</cotxe>
			<dataInici>2016-05-12</dataInici>
			<dataFi>2016-05-20</dataFi>
		</lloguer>
	</client>
	<client dni="42568536l">
		<nom tractament="Sra">Marta Soler</nom>
		<telefon>971235685</telefon>
		<email>psoler@gmail.com</email>
		<tipusClient>Ocasional</tipusClient>
		<lloguer>
			<cotxe>4256DRL</cotxe>
			<dataInici>2015-07-14</dataInici>
			<dataFi>2015-07-21</dataFi>
		</lloguer>
	</client>
</lloguerCotxes>
